apiVersion: v2
# UPDATE_HERE
version: 0.12.0
appVersion: 0.6.0
type: application
description: Helm chart deploys sops-secrets-operator
name: sops-secrets-operator
sources:
- https://github.com/isindir/sops-secrets-operator.git
maintainers:
- name: isindir
  email: isindir@users.sf.net
metadata:
  annotations:
    artifacthub.io/operator: "true"
    artifacthub.io/links:
    - name: "SOPS: Secrets OPerationS - Kubernetes Operator github project"
      url: "https://github.com/isindir/sops-secrets-operator.git"
    - name: "SOPS: Secrets OPerationS"
      url: "https://github.com/mozilla/sops"
    artifacthub.io/maintainers:
    - name: isindir
      email: isindir@users.sf.net
    artifacthub.io/operatorCapabilities: "Full Lifecycle"
    artifacthub.io/crds:
    - kind: SopsSecret
      version: isindir.github.com/v1alpha3
      name: sopssecret
      displayName: SopsSecret
      description: SopsSecret - encapsulates sops encrypted kubernetes secrets definitions
keywords:
- gitops
- sops
- kms
- encryption
