apiVersion: v2
version: 0.4.3
appVersion: 0.1.2
type: application
description: sops secrets operator
name: sops-secrets-operator
sources:
- https://github.com/isindir/sops-secrets-operator.git
maintainers:
- name: isindir
  email: isindir@users.sf.net
