apiVersion: v1
version: 0.3.1
appVersion: 0.1.1
description: sops secrets operator
name: sops-secrets-operator
sources:
- https://github.com/isindir/sops-secrets-operator.git
maintainers:
- name: isindir
  email: isindir@users.sf.net
